users:
  - name: vlad
    config:
      bot_token: 1864151853:AAHgkrk0iFlJIWWiacF4cNXIA4TbLChRjNE
      chat_id: -478897834
      onliner_params:
        - only_owner: true
        - rent_type[]: 1_room
        - rent_type[]: 2_rooms
        - rent_type[]: 3_rooms
        - price[min]: 300
        - price[max]: 500
        - currency: usd
        - bounds[lb][lat]: 53.81443127478178
        - bounds[lb][long]: 27.317984927108977
        - bounds[rt][lat]: 53.98436885620384
        - bounds[rt][long]: 27.56904397322554
        - order: last_time_up:desc
        - page: 1
      realt_params:
        url: https://realt.by/rent/flat-for-long/?search=eJx9T8sOgjAQ%2FJpybnmE9uBB5D82pV2UCJS0VeHvhSpKTPAymZ3ZneyM0KO00KG3hmQFkqw8sMibRw%2B97OaxaJvros6MLiYpKRGnBQsesCQlI5wFfoysMZ17B60ncTTYRi1Z55AfZ%2FSjtEFJZ2UELScHptXrH3kEDv1tmGfpFGh0apPK9lz24zpjPVTT5lRLj2Dx3rjG9DuL7M%2BiRQUDWhjkq1BCv94lNIxR5aLmqKXgcUVFjSrNEmRU0KRO%2BBO%2BU3DU